# Question Answering Leaderboard Example

In [1]:
import pandas as pd
import requests

In [ ]:
TEAM_NAME = "your_team_name"

In [ ]:
BASE_URL = "http://durham-leaderboard-runai-innovation-klemen.inference.compute.datascience.ch"
leaderboard_endpoint = f"{BASE_URL}/api/v1/leaderboard"
submit_endpoint = f"{BASE_URL}/api/v1/submit"


def get_leaderboard() -> pd.DataFrame:
    leaderboard = requests.get(leaderboard_endpoint).json()
    return pd.DataFrame(leaderboard["entries"])


def submit(df: pd.DataFrame, user: str, token: str) -> pd.Series:
    if user == "your_team_name" or user == "":
        raise ValueError("Please set your team name in the 'TEAM_NAME' variable.")
    predictions = df[["question", "answer"]].to_dict(orient="records")
    submission = {"predictions": predictions}
    response = requests.post(submit_endpoint, json=submission, auth=(user, token))
    if (response.status_code // 100) != 2:
        response.raise_for_status()
    print(response.json())
    return pd.Series(response.json())

In [3]:
get_leaderboard()

Empty DataFrame
Columns: []
Index: []

In [ ]:
df = pd.read_csv("../../data/a2q/qa_set.csv", encoding="utf-8", sep=";").fillna("")
df.head(10)

,question,answer
0,What year where there most casualties from man...,"2002. In that year more than 10,000 casualties..."
1,In what year did the quantity of man-made disa...,Man-made disasters peaked in 2005
2,Between 1970 and 2023 what year in the data sh...,2023. There were 218 instances of natural cat...
3,What year between 1994 and 2023 had the most h...,2011 with 6.
4,How much higher are the 2023 insured losses th...,They are higher by 21%.
5,Which figure shows the trend in insured losses...,
6,"Before 2023, what was the highest year on reco...",
7,What regions does the Swiss Re report on natur...,
8,What is the highest Benefit to Cost ratio buil...,
9,According to the Swiss Re Institute report on ...,

In [ ]:
submit(df, user=TEAM_NAME, token="cant_be_empty")

{'user_name': 'your_team_name', 'rank': 1, 'attempt': 1, 'timestamp': '2026-06-01T14:40:25.557770', 'metrics': {'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'difficulty': [2.0, 2.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 2.0, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 1.5, 1.0], 'total_score': 0.09174311926605505, 'questions_answered': 5, 'total_questions': 40}}

user_name                                       your_team_name
rank                                                         1
attempt                                                      1
timestamp                           2026-06-01T14:40:25.557770
metrics      {'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0,...
dtype: object

In [6]:
get_leaderboard()

,user_name,rank,attempt,timestamp,metrics
0,your_team_name,1,1,2026-06-01T14:40:25.557770,"{'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0,..."